---
- hosts: sr_hosts
  remote_user: root
  vars_files:
    - ./upgrade_vars.yml
  tasks:
    - name:  decompress new SR Software packages
      unarchive:
        src: "{{ new_pkg_path }}"
        dest: "{{ new_filepath }}"
        copy: yes

    - name: export java home for start_fe
      lineinfile: 
        path: "{{ new_fe_path }}/bin/start_fe.sh"
        insertafter: "# java"
        line: "export JAVA_HOME={{ java_home }}"
    - name: export java home for broker
      lineinfile:
        path: "{{ new_broker_path }}/bin/start_broker.sh"
        insertafter: "# java"
        line: "export JAVA_HOME={{ java_home }}"

- hosts: backends
  remote_user: root
  vars_files:
    - ./upgrade_vars.yml
  tasks:
    - name: update backends
      shell:
        cmd: 
          mv {{ new_be_path }}/conf/be.conf {{ new_be_path }}/conf/new_be.conf &&
          sh {{ be_path }}/bin/stop_be.sh &&
          cp -r {{ new_be_path }} {{ be_path }}/../ && 
          sh {{ be_path }}/bin/start_be.sh --daemon
- hosts: brokers
  remote_user: root
  vars_files:
    - ./upgrade_vars.yml
  tasks:
    - name: update brokers
      shell: 
        cmd: 
          mv {{ new_broker_path }}/conf/apache_hdfs_broker.conf {{ new_broker_path }}/conf/new_apache_hdfs_broker.conf &&
          sh {{ broker_path }}/bin/stop_broker.sh &&
          cp -r {{ new_broker_path }} {{ broker_path }}/../ &&
          sh {{ broker_path }}/bin/start_broker.sh --daemon 
- hosts: follower
  remote_user: root
  vars_files:
    - ./upgrade_vars.yml
  tasks:
    - name:
      shell:
        cmd:  
          mv {{ new_fe_path }}/conf/fe.conf {{ new_fe_path }}/conf/new_fe.conf &&
          sh {{ fe_path }}/bin/stop_fe.sh &&
          cp -r {{ new_fe_path }} {{ fe_path }}/../ &&
          sh {{ fe_path }}/bin/start_fe.sh --daemon
- hosts: master
  remote_user: root
  vars_files:
    - ./upgrade_vars.yml
  tasks:
    - name:
      shell:
        cmd: 
          mv {{ new_fe_path }}/conf/fe.conf {{ new_fe_path }}/conf/new_fe.conf &&
          sh {{ fe_path }}/bin/stop_fe.sh &&
          cp -r {{ new_fe_path }} {{ fe_path }}/../ &&
          sh {{ fe_path }}/bin/start_fe.sh --daemon 
